spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 3621
    url: jdbc:postgresql://localhost:5433/core-spring-security

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
